module.exports = Object.freeze({
    TM_TYPING_FULLMATCH: 0,
    TM_TYPING_PARTMATCH: 1,
    TM_TYPING_TYPO: 2,
    TM_TYPING_TYPO_RESET: 3,
    TM_TYPING_TYPO_NO_MATCH: 4,
    TM_TYPING_NOTHING: 5,
});